Liberal:
  name: Liberal
  state: TAS
Network:
  name: Jacqui Lambie Network
  state: TAS
Labor:
  name: Labor
  state: TAS
Greensn:
  name: Greens
  state: TAS
Independent:
  name: Independent
  state: TAS
