# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/leader_profiles' do
  # This should return the minimal set of attributes required to create a valid
  # LeaderProfile. As you add validations to LeaderProfile, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      LeaderProfile.create! valid_attributes
      get _leader_profiles_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      leader_profile = LeaderProfile.create! valid_attributes
      get _leader_profile_url(leader_profile)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new__leader_profile_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      leader_profile = LeaderProfile.create! valid_attributes
      get edit__leader_profile_url(leader_profile)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new LeaderProfile' do
        expect do
          post _leader_profiles_url, params: { leader_profile: valid_attributes }
        end.to change(LeaderProfile, :count).by(1)
      end

      it 'redirects to the created leader_profile' do
        post _leader_profiles_url, params: { leader_profile: valid_attributes }
        expect(response).to redirect_to(_leader_profile_url(LeaderProfile.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new LeaderProfile' do
        expect do
          post _leader_profiles_url, params: { leader_profile: invalid_attributes }
        end.to_not change(LeaderProfile, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post _leader_profiles_url, params: { leader_profile: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested leader_profile' do
        leader_profile = LeaderProfile.create! valid_attributes
        patch _leader_profile_url(leader_profile), params: { leader_profile: new_attributes }
        leader_profile.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the leader_profile' do
        leader_profile = LeaderProfile.create! valid_attributes
        patch _leader_profile_url(leader_profile), params: { leader_profile: new_attributes }
        leader_profile.reload
        expect(response).to redirect_to(leader_profile_url(leader_profile))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        leader_profile = LeaderProfile.create! valid_attributes
        patch _leader_profile_url(leader_profile), params: { leader_profile: invalid_attributes }
        expect(response).to have_http_status(422)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested leader_profile' do
      leader_profile = LeaderProfile.create! valid_attributes
      expect do
        delete _leader_profile_url(leader_profile)
      end.to change(LeaderProfile, :count).by(-1)
    end

    it 'redirects to the leader_profiles list' do
      leader_profile = LeaderProfile.create! valid_attributes
      delete _leader_profile_url(leader_profile)
      expect(response).to redirect_to(_leader_profiles_url)
    end
  end
end
